### ISSUE TITLE
 Can this method be used for indoor datasets?

### ISSUE THREAD

**Issue by zhangxin-516** [gmberton/EigenPlaces#10]
Thank you very much for your sharing. Were all the datasets used for testing your method outdoor datasets? Have you applied your method to indoor retrieval? Looking forward to your reply.

**Comment by gmberton** [comment]
Hi, EigenPlaces can be used for indoor retrieval but I don't expect it to work well. If you want a model that works well indoor, you can try the `eigenplaces-indoor` or `salad-indoor` from [this other repo](https://github.com/gmberton/VPR-methods-evaluation)
