### ISSUE TITLE
Hello, if I want to convert this model to onnx format, what should I do?

### ISSUE THREAD

**Issue by kai-kai-tang** [gmberton/EigenPlaces#13]

**Comment by gmberton** [comment]
Hi, you can [check this link out](https://pytorch.org/tutorials/beginner/onnx/export_simple_model_to_onnx_tutorial.html) which is about converting torch models to onnx.
I never did that, so I don't know how to do it, but if you have questions about our code feel free to ask

**Comment by kai-kai-tang** [comment]
OK, thank you very much for your reply
