### ISSUE TITLE
Finetune on CosPlace weights

### ISSUE THREAD

**Issue by ShihaoShao-GH** [gmberton/EigenPlaces#2]
Hi, me again. Thank you for your answer before to make sure my number is correct! I really like EigenPlaces, so I kept diving into the detail of your great work. Then I got another confusion and really hope you can help to make it clear. 

I saw from the code that your model is trained on the top of the CosPlace pre-trained weight. Since I did not find the corresponding description in your paper (I might missed that), I wonder whether this behaviour is desired, or we are supposed to fine-tune the weight on ImageNet pre-train weights? 

Each of them sounds reasonable for me (so the paper is grounded in contribution whether the truth goes either way). I just want to make clear this detail:) Thank you again for your help! And hope to see your works again in CVPR 2024. I really like such type of easy-reproducing works which helps the community a lot.

**Comment by gmberton** [comment]
Hi, indeed EigenPlaces starts training from CosPlace's weights as in the code, not from ImageNet's pre-trained weights.

I agree that the contribution is strong even like this, but I also think that we should have explicitely written it in the paper, as I believe that a paper should contain all the details to make it reproducible (I just checked the paper again and it's not written there).
So I apologize about that, we might have missed it in the rush of the submission.

Regarding CVPR 2024, I'm not currently working on this "standard VPR" setting at the moment but on similar topics: anyway I will always make sure that my papers are fair and reproducible, and I wish more people did the same :-)

**Comment by ShihaoShao-GH** [comment]
Thanks for quick clarifying. It helps reproduce the result!
