### ISSUE TITLE
Evaluattion on custom dataset captured on vehicle

### ISSUE THREAD

**Issue by ur10** [gmberton/EigenPlaces#5]
Hello @gmberton, thank you for the work. I am trying to evaluate the EigenPlaces method on a custom dataset that is captured on a car. I was wondering  how to identify if I can use my data as a multiview one or not. This is my schematic for capture - 
![image](https://github.com/gmberton/EigenPlaces/assets/37475612/3bac8780-555b-41b2-b9e8-3d4f85ebd3c5)
The paper says "_This method assumes that the images available in the database are collected looking at all sides of the vehicle, and
in particular towards the side of the street. However, this is not always the case and many VPR datasets: for example, the datasets built with autonomous driving applications in mind only contain images collected from a front facing camera_"

Do you think a capture as shown above qualifies as multiview?

**Comment by gmberton** [comment]
Hi, thank you for your question.
1) Yes, I think your dataset qualifies as multiview.
2) However if you're using your dataset only for evaluation, then the dataset doesn't need to be multiview: at test-time it works on both single-view (like St Lucia) and multi-view datasets.

If you want to evaluate EigenPlaces on your dataset, just rename your images with the format
`@UTM_east@UTM_north@....jpg`
where `UTM_east` and `UTM_north` are UTM coordinates, which can be directly obtained from latitude and longitude simply like this (after `pip install utm`)
```
import utm
utm_east, utm_north = utm.from_latlon(lat, lon)[:2]
```
and the dots `...` in the filename can be any value (e.g. the original filename).
Then put your database images in a folder called `my_dataset/database` and the queries in `my_dataset/queries`, then just run this command to evaluate the model 
`python3 eval.py --backbone ResNet50 --fc_output_dim 2048 --resume_model torchhub --test_dataset_folder ./my_dataset`

**Comment by ur10** [comment]
Got it. Thanks a lot for the help!
