### ISSUE TITLE
apply the EigenPlaces to drone view with satellite view

### ISSUE THREAD

**Issue by songkemail** [gmberton/EigenPlaces#7]
hi, gmberton, thank you again.
the EigenPlaces outperform SOTA on cross view street images VPR. As the  uav image and satellite image has the same location but different viewpoint. does the EigenPlaces adapt to drone view and satellite view VPR eg given one uav image find the simalry satellite image.
How about retrain the model on paired uav images and satallite dataset to make it possible or some other work need to do? any suggestion appreciate.

**Comment by gmberton** [comment]
Hi, I don't think EigenPlaces would work on satellite images.
My advice is to check Cross-View Image Geo-localization papers, which are designed for that

**Comment by songkemail** [comment]
Thank you
