### ISSUE TITLE
train dataset

### ISSUE THREAD

**Issue by WeilongXia** [gmberton/EigenPlaces#8]
Thank you for your excellent work, but I have a question I'd like to ask. What if I want to create my own training dataset, are training datasets limited to only using panoramic images?

**Comment by gmberton** [comment]
In the code I use panoramic images which are then cropped according to the required angle, but it would be okay to directly use the images which have angle equal (or close to) the one required, though that would need some effort to re write the training dataset

**Comment by WeilongXia** [comment]
Thanks for your answer, so should I use image pointing to focal point? But doesn’t the paper also cluster the images in the cell by calculating the alpha angle obtained by connecting the camera orientation and the focal point? Looking forward to your reply.

**Comment by gmberton** [comment]
All images within a class point to the same focal point. To find the images that point towards the focal point, we need to compute the alpha angle, which is dependent on the image's position

**Comment by WeilongXia** [comment]
Okay, thanks for your answer.
